name: squad2
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.8.0
  - ujson
  - numpy
  - pip
  - spacy=2.0.16
  - tensorboard
  - tensorflow
  - tensorboardX
  - tqdm
  - urllib3
  - pip:
    - torch==1.9.0
